// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News___WebAPI.Repositories;

#nullable disable

namespace News___WebAPI.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260923133827_SeedDataEklendi")]
    partial class SeedDataEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("News___WebAPI.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsArticlesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ahmet Yılmaz",
                            Content = "Yapay zeka destekli araçlar, test otomasyonundan kod optimizasyonuna kadar tüm yazılım yaşam döngüsünü kökten değiştiriyor. Geliştiriciler rutin görevleri devrederken mimari tasarıma daha fazla odaklanabiliyor...",
                            PublishedAt = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Slug = "yapay-zeka-ve-yazilim-dunyasindaki-yeni-gelismeler",
                            Status = "Published",
                            Summary = "Yapay zeka teknolojilerinin modern yazılım geliştirme süreçlerine etkileri ve sektörel beklentiler.",
                            Title = "Yapay Zeka ve Yazılım Dünyasındaki Yeni Gelişmeler"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Selin Demir",
                            Content = ".NET 10 sürümüyle birlikte runtime üzerinde yapılan derinlemesine iyileştirmeler sayesinde Web API uç noktalarında yanıt süreleri ciddi oranda düşmüş durumda...",
                            PublishedAt = new DateTime(2026, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "dotnet-10-ile-gelen-performans-iyilestirmeleri",
                            Status = "Published",
                            Summary = "Yeni .NET sürümünün getirdiği JIT optimizasyonları ve bellek yönetimi avantajları.",
                            Title = ".NET 10 ile Gelen Performans İyileştirmeleri"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Burak Kaya",
                            Content = "Monolitik yapıdan mikroservislere geçerken karşılaşılan en büyük zorluklardan biri veritabanı ayrımıdır. Bu yazıda Outbox Pattern ve event-driven çözümleri ele alıyoruz...",
                            Slug = "mikroservis-mimarilerinde-veri-tutarliigi",
                            Status = "Draft",
                            Summary = "Dağıtık sistemlerde ACID yerine nihai tutarlılık (eventual consistency) prensipleri.",
                            Title = "Mikroservis Mimarilerinde Veri Tutarlılığı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
